
name: Build and Push Multiple Images to ACR
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: |
        az acr login -n ${{ secrets.ACR_NAME }}

    - name: Build and Push catalog image
      run: |
        IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/catalog-svc:v1.0.7
        docker build -t $IMAGE ./apps/catalog-svc
        docker push $IMAGE

    - name: Build and Push identity image
      run: |
        IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/identity-svc:v1.0.7
        docker build -t $IMAGE ./apps/identity-svc
        docker push $IMAGE

    - name: Build and Push order image
      run: |
        IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/order-svc:v1.0.7
        docker build -t $IMAGE ./apps/order-svc
        docker push $IMAGE
    
    - name: Build and Push webapp image
      run: |
        IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/webapp:v1.0.9
        docker build -t $IMAGE ./apps/webapp
        docker push $IMAGE